name = "human-market-cap"
main = "./worker/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "human-market-cap"
database_id = "08431a90-97e9-4b8b-bc43-d7c7ebc524b5"
migrations_dir = "drizzle"

[images]
binding = "IMAGES"
