"use client";

import { type FormEvent, type ReactNode, useEffect, useMemo, useRef, useState } from "react";
import {
  APPEARANCES, EDUCATIONS, OCCUPATIONS, QUIZ_BANK,
  type AnnualProjection, type AppearanceKey, type CalculatorInputs, type CalculationResult,
  type EducationKey, type OccupationKey, type QuizQuestion,
  calculateMarketCap, formatMan, formatPercent, getAppearance, getEducation,
  getOccupation, getTier, miniWageCurve,
} from "./model";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, "") ?? "";
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";
type InputState = Omit<CalculatorInputs,"correctAnswers">;
type RankingMode = "global"|"demo";
interface Ranking { rank:number; total:number; deviation:number; topPercent:number; scores:number[]; mode:RankingMode; }
interface DisplayResult { calculation:CalculationResult; scoreYen:number; previousScoreYen:number|null; }

const DEFAULTS:InputState={age:30,annualIncome:600,education:"university",appearance:"middle",occupation:"listed",financialAssets:300,realEstateAssets:0,reinvestmentRate:.2};

function pickQuestions(){const list=[...QUIZ_BANK];for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list.slice(0,5);}
function uid(){const key="hmc_uid",old=localStorage.getItem(key);if(old)return old;const value=crypto?.randomUUID?.()??`hmc-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(key,value);return value;}
function demoScores(){return Array.from({length:180},(_,i)=>Math.round((650+Math.pow(i/179,2.35)*68000+(i%9)*55)*10000));}
function rankScores(source:number[],score:number,mode:RankingMode):Ranking{
  const scores=source.some(x=>Math.abs(x-score)<1)?[...source]:[...source,score];scores.sort((a,b)=>b-a);
  const index=scores.findIndex(x=>x<=score),rank=(index<0?scores.length-1:index)+1,mean=scores.reduce((a,b)=>a+b,0)/scores.length;
  const sd=Math.sqrt(scores.reduce((sum,x)=>sum+(x-mean)**2,0)/scores.length);
  return {rank,total:scores.length,deviation:sd?Math.min(99,Math.max(1,50+(score-mean)/sd*10)):50,topPercent:rank/scores.length*100,scores,mode};
}
async function saveRanking(score:number):Promise<Ranking>{
  if(!SUPABASE_URL||!SUPABASE_ANON_KEY)return rankScores(demoScores(),score,"demo");
  const headers={apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,"Content-Type":"application/json"};
  const saved=await fetch(`${SUPABASE_URL}/rest/v1/hmc_scores?on_conflict=uid`,{method:"POST",headers:{...headers,Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({uid:uid(),score,updated_at:new Date().toISOString()})});
  if(!saved.ok)throw new Error("upsert");
  const response=await fetch(`${SUPABASE_URL}/rest/v1/hmc_scores?select=score&order=score.desc&limit=1000`,{headers});if(!response.ok)throw new Error("select");
  const rows=await response.json() as {score:number|string}[];return rankScores(rows.map(x=>Number(x.score)).filter(Number.isFinite),score,"global");
}

function MiniCurve({occupation}:{occupation:OccupationKey}){const points=miniWageCurve(getOccupation(occupation)),max=Math.max(...points);return <div className="mini-curve" aria-label="賃金カーブプレビュー">{points.map((x,i)=><span key={i} style={{height:`${Math.max(10,x/max*100)}%`}}/>)}</div>}

function SalaryCanvas({data,width}:{data:AnnualProjection[];width:number}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const canvas=ref.current;if(!canvas||!data.length)return;const h=272,dpr=window.devicePixelRatio||1;canvas.width=width*dpr;canvas.height=h*dpr;canvas.style.width=`${width}px`;canvas.style.height=`${h}px`;const c=canvas.getContext("2d");if(!c)return;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,width,h);
    const left=54,top=32,bottom=30,ch=h-top-bottom,max=Math.max(100,...data.map(x=>x.salary))*1.18;c.font="10px 'DM Mono',monospace";c.textAlign="right";
    for(let t=0;t<=4;t++){const y=top+ch-ch*t/4;c.strokeStyle="#292722";c.beginPath();c.moveTo(left,y);c.lineTo(width-20,y);c.stroke();c.fillStyle="#77736b";c.fillText(`${Math.round(max*t/4).toLocaleString("ja-JP")}万`,left-8,y+3);}
    c.strokeStyle="#4a9eff";c.lineWidth=2.5;c.beginPath();data.forEach((x,i)=>{const px=left+i*56+28,py=top+ch-x.salary/max*ch;i?c.lineTo(px,py):c.moveTo(px,py);});c.stroke();
    data.forEach((x,i)=>{const px=left+i*56+28,py=top+ch-x.salary/max*ch;c.fillStyle="#0a0a0a";c.strokeStyle="#4a9eff";c.lineWidth=2;c.beginPath();c.arc(px,py,4,0,Math.PI*2);c.fill();c.stroke();c.fillStyle="#b8d6ff";c.font="9px 'DM Mono',monospace";c.textAlign="center";c.fillText(`${Math.round(x.salary).toLocaleString("ja-JP")}万`,px,Math.max(12,py-10-(i%2)*11));});
  },[data,width]);return <canvas ref={ref} role="img" aria-label="年齢別の期待年収推移"/>;
}

function Charts({result}:{result:CalculationResult}){const data=result.projections;if(!data.length)return <p className="empty-note">引退年齢を超えているため、残余期間のチャートはありません。</p>;const width=74+data.length*56,max=Math.max(1,...data.map(x=>x.balance));return <div className="chart-scroll"><div className="chart-stage" style={{width}}>
  <div className="chart-heading-row"><div><span className="eyebrow">INCOME CURVE</span><h4>年収推移</h4></div><span className="legend-dot blue">期待年収</span></div><SalaryCanvas data={data} width={width}/>
  <div className="chart-heading-row asset-heading"><div><span className="eyebrow">ASSET BUILD-UP</span><h4>資産推移</h4></div><div className="asset-legend"><span className="legend-dot purple">初期</span><span className="legend-dot green">再投資</span><span className="legend-dot gold">運用益</span></div></div>
  <div className="asset-chart" style={{paddingLeft:54,paddingRight:20}}>{data.map(x=><div className="asset-column" key={x.age}><span className="asset-total">{Math.round(x.balance).toLocaleString("ja-JP")}万</span><div className="asset-bar" title={`${x.age}歳：${formatMan(x.balance)}`}><span className="asset-layer gain" style={{height:Math.max(0,x.gains/max*158)}}/><span className="asset-layer reinvested" style={{height:Math.max(0,x.reinvested/max*158)}}/><span className="asset-layer initial" style={{height:Math.max(2,x.initialAssets/max*158)}}/></div>{x.gains<0&&<span className="loss-mark">LOSS</span>}<span className="age-label">{x.age}歳</span></div>)}</div>
  </div></div>}

function Histogram({ranking,score}:{ranking:Ranking;score:number}){const min=Math.min(...ranking.scores),max=Math.max(...ranking.scores),span=Math.max(1,max-min),bins=Array.from({length:12},()=>0);ranking.scores.forEach(x=>bins[Math.min(11,Math.floor((x-min)/span*12))]++);const peak=Math.max(...bins,1),marker=Math.min(100,Math.max(0,(score-min)/span*100));return <div className="histogram-wrap"><div className="you-marker" style={{left:`${marker}%`}}><span>YOU</span></div><div className="histogram">{bins.map((x,i)=><span key={i} style={{height:`${Math.max(5,x/peak*100)}%`}}/>)}</div><div className="histogram-axis"><span>LOW</span><span>MARKET VALUE</span><span>HIGH</span></div></div>}
function Trace({title,children}:{title:string;children:ReactNode}){return <details className="trace"><summary>{title}<span>＋</span></summary><div>{children}</div></details>}
function Factor({label,value,caption}:{label:string;value:number;caption:string}){return <div className="factor-row"><div className="factor-head"><span>{label}</span><strong>{caption}</strong></div><div className="factor-track"><span style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div></div>}
function notes(r:CalculationResult){return [r.occupation.careerRisk>=.2?`キャリアリスクが年率${(r.occupation.careerRisk*100).toFixed(0)}%と高水準です。収入源の複線化が最大の改善余地です。`:r.occupation.careerRisk<=.02?"キャリア持続性が高く、長期間の給与キャッシュフローが評価を下支えしています。":"キャリアの成長余地と継続リスクは中位です。専門性の更新が評価維持の鍵になります。",r.effectiveReturn>=.045?"実効利回りは上限に近い水準です。追加リターンより、分散と下方リスク管理が重要です。":r.effectiveReturn<.01?"資産運用の寄与が弱く、金融リテラシーの改善効果が大きい状態です。":"資産所得は健全な補助エンジンです。再投資率を維持すると後半ほど複利が効きます。",r.yearsRemaining<10?"残余就労年数が短いため、既存資産の保全とキャッシュフロー設計が優先です。":`残余就労年数は${r.yearsRemaining}年。小さな成長率差でも累計価値には大きく効く時間軸です。`];}

export default function HumanMarketCapApp(){
  const [inputs,setInputs]=useState<InputState>(DEFAULTS),[questions,setQuestions]=useState<QuizQuestion[]>([]),[answers,setAnswers]=useState<Record<string,number>>({}),[error,setError]=useState(""),[display,setDisplay]=useState<DisplayResult|null>(null),[ranking,setRanking]=useState<Ranking|null>(null);const resultRef=useRef<HTMLElement>(null);
  useEffect(()=>{setQuestions(pickQuestions());uid();},[]);
  const education=useMemo(()=>getEducation(inputs.education),[inputs.education]),appearance=useMemo(()=>getAppearance(inputs.appearance),[inputs.appearance]),job=useMemo(()=>getOccupation(inputs.occupation),[inputs.occupation]);
  const number=(key:"age"|"annualIncome"|"financialAssets"|"realEstateAssets"|"reinvestmentRate",value:number)=>setInputs(s=>({...s,[key]:Number.isFinite(value)?value:0}));
  const refresh=async(score:number)=>{try{setRanking(await saveRanking(score));}catch{setRanking(rankScores(demoScores(),score,"demo"));}};
  function submit(e:FormEvent){e.preventDefault();if(questions.length!==5||questions.some(q=>answers[q.id]===undefined)){setError("金融リテラシーテストの5問すべてに回答してください。");document.getElementById("question-9")?.scrollIntoView({behavior:"smooth"});return;}if(inputs.age<18||inputs.age>80||inputs.annualIncome<0||inputs.reinvestmentRate<0||inputs.reinvestmentRate>1){setError("年齢・年収・再投資率の入力値を確認してください。");return;}setError("");const correct=questions.filter(q=>answers[q.id]===q.answer).length,calculation=calculateMarketCap({...inputs,correctAnswers:correct}),scoreYen=Math.round(calculation.marketCapMan*10000),previous=localStorage.getItem("hmc_previous_score");localStorage.setItem("hmc_previous_score",String(scoreYen));setDisplay({calculation,scoreYen,previousScoreYen:previous===null?null:Number(previous)});setRanking(null);void refresh(scoreYen);setTimeout(()=>resultRef.current?.scrollIntoView({behavior:"smooth"}),80);}
  const r=display?.calculation,tier=r?getTier(r.marketCapMan):"D",correct=r?Math.round((r.financialAdjustment/.1+.5)*5):0;
  return <main><div className="app-shell">
    <header className="brand-bar"><a className="brand" href="#top"><span className="brand-mark">HMC</span><span>HUMAN CAPITAL<br/>DESK</span></a><span className="model-tag">DCF MODEL / v13</span></header>
    <section className="intro" id="top"><p className="eyebrow">PRICE YOUR POTENTIAL</p><h1>あなたの価値を、<br/><em>数字にする。</em></h1><p className="intro-copy">属性・資産・金融知識から、残りのキャリアが生み出す価値をDCF的に査定します。</p><div className="formula-strip"><span>給与所得総額</span><b>＋</b><span>資産所得総額</span><b>＝</b><strong>時価総額</strong></div><div className="trust-row"><span>01 / 匿名</span><span>02 / 約3分</span><span>03 / 最新スコアのみ</span></div></section>
    <form className="calculator-form" onSubmit={submit} noValidate><div className="form-heading"><div><span className="eyebrow">VALUATION SHEET</span><h2>査定情報</h2></div><span>9 QUESTIONS</span></div>
      <section className="question-card"><label htmlFor="age"><span className="question-number">01</span><span>現在の年齢</span></label><div className="number-input"><input id="age" type="number" inputMode="numeric" min="18" max="80" value={inputs.age} onChange={e=>number("age",Number(e.target.value))}/><span>歳</span></div><p className="field-note">職業別の引退年齢までを残余就労期間として計算</p></section>
      <section className="question-card"><label htmlFor="income"><span className="question-number">02</span><span>現在の年収</span></label><div className="number-input"><input id="income" type="number" inputMode="decimal" min="0" value={inputs.annualIncome} onChange={e=>number("annualIncome",Number(e.target.value))}/><span>万円</span></div><p className="field-note">額面年収。将来の賃金カーブの起点になります</p></section>
      <section className="question-card"><label htmlFor="education"><span className="question-number">03</span><span>最終学歴</span></label><select id="education" value={inputs.education} onChange={e=>setInputs(s=>({...s,education:e.target.value as EducationKey}))}>{EDUCATIONS.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select><div className="parameter-card"><div><span>学歴乗数</span><strong>×{education.multiplier.toFixed(2)}</strong></div><div><span>年収起点</span><strong>{formatPercent(education.salaryAdj)}</strong></div><div><span>NW力</span><strong>{education.nw}</strong></div><div><span>利回り</span><strong>{formatPercent(education.nwReturn)}</strong></div></div></section>
      <section className="question-card"><fieldset><legend><span className="question-number">04</span><span>容姿</span></legend><div className="choice-grid five">{APPEARANCES.map(x=><label key={x.key} className={inputs.appearance===x.key?"selected":""}><input type="radio" name="appearance" checked={inputs.appearance===x.key} onChange={()=>setInputs(s=>({...s,appearance:x.key as AppearanceKey}))}/><span>{x.label}</span></label>)}</div></fieldset><div className="parameter-card two"><div><span>給与成長ベース</span><strong>{formatPercent(appearance.salaryBase)}</strong></div><div><span>利回りベース</span><strong>{formatPercent(appearance.returnBase)}</strong></div></div></section>
      <section className="question-card"><label htmlFor="occupation"><span className="question-number">05</span><span>現在の職業</span></label><select id="occupation" value={inputs.occupation} onChange={e=>setInputs(s=>({...s,occupation:e.target.value as OccupationKey}))}>{OCCUPATIONS.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select><div className="occupation-card"><div className="occupation-stats"><div><span>RETIRE</span><strong>{job.retirement}</strong></div><div><span>PEAK</span><strong>{job.peak}</strong></div><div><span>RETURN</span><strong>{(job.baseReturn*100).toFixed(1)}%</strong></div><div><span>RISK</span><strong>{(job.careerRisk*100).toFixed(0)}%</strong></div></div><div className="curve-preview"><span>WAGE CURVE PREVIEW</span><MiniCurve occupation={inputs.occupation}/></div><div className="risk-line"><span>容姿影響 ×{job.appearanceMultiplier.toFixed(1)}</span><b className={`risk-badge risk-${job.riskLabel.toLowerCase().replace(/\s/g,"-")}`}>{job.riskLabel}</b></div></div></section>
      <section className="question-card"><label htmlFor="financial"><span className="question-number">06</span><span>現金・金融資産</span></label><div className="number-input"><input id="financial" type="number" inputMode="decimal" min="0" value={inputs.financialAssets} onChange={e=>number("financialAssets",Number(e.target.value))}/><span>万円</span></div></section>
      <section className="question-card"><label htmlFor="realestate"><span className="question-number">07</span><span>不動産資産</span></label><div className="number-input"><input id="realestate" type="number" inputMode="decimal" min="0" value={inputs.realEstateAssets} onChange={e=>number("realEstateAssets",Number(e.target.value))}/><span>万円</span></div><p className="field-note">現金・金融資産と合算して初期資産に計上</p></section>
      <section className="question-card"><label htmlFor="reinvestment"><span className="question-number">08</span><span>給与からの再投資率</span></label><div className="range-head"><strong>{Math.round(inputs.reinvestmentRate*100)}%</strong><span>推奨 20%以上</span></div><input id="reinvestment" className="range-input" type="range" min="0" max="80" value={Math.round(inputs.reinvestmentRate*100)} onChange={e=>number("reinvestmentRate",Number(e.target.value)/100)}/><div className="range-scale"><span>0%</span><span>40%</span><span>80%</span></div></section>
      <section className="question-card quiz-card" id="question-9"><div className="quiz-title"><span className="question-number">09</span><div><span>金融リテラシーテスト</span><small>5 / {QUIZ_BANK.length} RANDOM QUESTIONS</small></div></div>{questions.length===0?<p className="quiz-loading">問題を準備しています…</p>:questions.map((q,qi)=><fieldset className="quiz-question" key={q.id}><legend><span>Q{qi+1}</span>{q.question}</legend><div className="quiz-options">{q.options.map((option,oi)=><label key={option} className={answers[q.id]===oi?"selected":""}><input type="radio" name={q.id} checked={answers[q.id]===oi} onChange={()=>setAnswers(a=>({...a,[q.id]:oi}))}/><i>{String.fromCharCode(65+oi)}</i><span>{option}</span></label>)}</div></fieldset>)}<p className="quiz-impact">正答数に応じて、実効利回りが −5% 〜 ＋5% 補正されます。</p></section>
      {error&&<p className="form-error" role="alert">{error}</p>}<button className="calculate-button" type="submit" disabled={questions.length!==5}><span>時価総額を算出する</span><b>→</b></button><p className="privacy-note">入力内容はランキング用スコア以外保存しません。この結果は金融助言ではなく、教育・娯楽目的の試算です。</p>
    </form>
    {display&&r&&<section className="results" ref={resultRef}><div className="result-divider"><span>VALUATION REPORT</span><b>査定完了</b></div>
      <section className={`market-hero tier-${tier}`}><div className="hero-badges"><span className="tier-badge">{tier} TIER</span><span className={`risk-badge risk-${r.occupation.riskLabel.toLowerCase().replace(/\s/g,"-")}`}>{r.occupation.riskLabel} RISK</span></div><p>あなたの人間時価総額</p><h2>{formatMan(r.marketCapMan)}</h2><span className="hero-en">ESTIMATED HUMAN MARKET CAPITAL</span><Trace title="時価総額の計算トレース"><p>給与所得 {formatMan(r.salaryIncomeMan)} ＋ 資産所得 {formatMan(r.assetIncomeMan)}</p><p>残余{r.yearsRemaining}年の期待キャッシュフローを全補正で調整しています。</p></Trace></section>
      {display.previousScoreYen!==null&&<div className={`delta-banner ${display.scoreYen>=display.previousScoreYen?"positive":"negative"}`}><span>前回査定との差分</span><strong>{display.scoreYen>=display.previousScoreYen?"＋":"−"}{formatMan(Math.abs(display.scoreYen-display.previousScoreYen)/10000)}</strong></div>}
      <section className="result-card ranking-card"><div className="section-title"><div><span className="eyebrow">MARKET POSITION</span><h3>市場ポジション</h3></div><span className={`connection ${ranking?.mode==="global"?"online":""}`}>{ranking?.mode==="global"?"LIVE":"DEMO"}</span></div>{ranking?<><div className="ranking-kpis"><div><span>総合順位</span><strong><em>{ranking.rank}</em> / {ranking.total}</strong></div><div><span>偏差値</span><strong><em>{ranking.deviation.toFixed(1)}</em></strong></div><div><span>上位</span><strong><em>{ranking.topPercent.toFixed(1)}</em>%</strong></div></div><Histogram ranking={ranking} score={display.scoreYen}/>{ranking.mode==="demo"&&<p className="demo-note">Supabase接続前のため、比較用デモ分布で順位を表示しています。</p>}</>:<div className="ranking-loading"><span/>ランキングを照合しています…</div>}</section>
      <section className="kpi-grid"><article className="result-card kpi-card"><span className="kpi-icon blue">01</span><p>給与所得総額</p><h3>{formatMan(r.salaryIncomeMan)}</h3><Trace title="給与所得の計算トレース"><p>年収起点へ職業カーブ・インフレ2%・NW力・容姿・生存率を毎年適用。</p><p>累計に学歴乗数 ×{r.education.multiplier.toFixed(2)} を反映。</p></Trace></article><article className="result-card kpi-card"><span className="kpi-icon gold">02</span><p>資産所得総額</p><h3>{formatMan(r.assetIncomeMan)}</h3><Trace title="資産所得の計算トレース"><p>初期資産 {formatMan(inputs.financialAssets+inputs.realEstateAssets)} に年収の{Math.round(inputs.reinvestmentRate*100)}%を毎年追加。</p><p>実効利回り {(r.effectiveReturn*100).toFixed(2)}% で複利運用。</p></Trace></article></section>
      <section className="result-card charts-card"><div className="section-title"><div><span className="eyebrow">LIFETIME PROJECTION</span><h3>生涯キャッシュフロー</h3></div><span className="scroll-hint">← SWIPE →</span></div><Charts result={r}/></section>
      <section className="result-card assumptions-card"><div className="section-title"><div><span className="eyebrow">APPLIED ASSUMPTIONS</span><h3>試算の前提条件</h3></div></div><div className="assumption-list"><div><span>残余就労年数</span><strong>{r.yearsRemaining}年（{inputs.age}→{r.occupation.retirement}歳）</strong></div><div><span>学歴乗数</span><strong>×{r.education.multiplier.toFixed(2)}</strong></div><div><span>年収起点補正</span><strong>{formatPercent(r.education.salaryAdj)}</strong></div><div><span>インフレ補正</span><strong>＋2.0% / 年</strong></div><div><span>NW→給与</span><strong>{formatPercent(r.education.nwSalary)}</strong></div><div><span>容姿→給与</span><strong>{formatPercent(r.appearanceSalaryAdjustment)}</strong></div><div><span>職業別基本利回り</span><strong>{formatPercent(r.occupation.baseReturn)}</strong></div><div><span>金融リテラシー</span><strong>{correct} / 5問・{formatPercent(r.financialAdjustment)}</strong></div><div><span>NW→利回り</span><strong>{formatPercent(r.education.nwReturn)}</strong></div><div><span>容姿→利回り</span><strong>{formatPercent(r.appearanceReturnAdjustment)}</strong></div><div className="highlight"><span>実効利回り</span><strong>{(r.effectiveReturn*100).toFixed(2)}%（上限5.0%）</strong></div><div><span>キャリアリスク</span><strong>{(r.occupation.careerRisk*100).toFixed(0)}% / 年</strong></div></div></section>
      <section className="result-card factors-card"><div className="section-title"><div><span className="eyebrow">VALUATION FACTORS</span><h3>評価ファクター</h3></div></div><Factor label="金融リテラシー" value={correct/5*100} caption={`${correct}/5`}/><Factor label="実効利回り" value={(r.effectiveReturn+.05)/.1*100} caption={`${(r.effectiveReturn*100).toFixed(2)}%`}/><Factor label="NW力" value={r.education.nw} caption={`${r.education.nw}`}/><Factor label="容姿補正" value={50+r.appearanceSalaryAdjustment*400} caption={formatPercent(r.appearanceSalaryAdjustment)}/><Factor label="キャリア持続性" value={(1-r.occupation.careerRisk)*100} caption={`${((1-r.occupation.careerRisk)*100).toFixed(0)}%`}/><Factor label="残余就労年数" value={r.yearsRemaining/50*100} caption={`${r.yearsRemaining}年`}/></section>
      <section className="result-card analysis-card"><div className="section-title"><div><span className="eyebrow">ANALYST NOTES</span><h3>分析コメント</h3></div></div><div className="analyst-stamp"><span>{tier}</span><div><strong>{tier==="S"?"超優良人材":tier==="A"?"成長優良人材":tier==="B"?"安定成長人材":tier==="C"?"改善余地あり":"再建プラン推奨"}</strong><small>HMC ANALYST RATING</small></div></div><ol>{notes(r).map(x=><li key={x}>{x}</li>)}</ol><p className="risk-warning"><b>RISK NOTICE</b> この査定は入力条件に基づく期待値です。実際の収入・運用成果を保証するものではありません。</p></section>
      <button className="revise-button" type="button" onClick={()=>{setDisplay(null);setRanking(null);scrollTo({top:0,behavior:"smooth"});}}>条件を修正して再計算する</button>
    </section>}
    <footer><span>HMC CALCULATOR / v13</span><p>ENTERTAINMENT × FINANCIAL EDUCATION</p></footer>
  </div></main>;
}
