import type { CatalogEntry } from "./types.ts";

export const COMMENT_CATALOG: CatalogEntry[] = [
  {
    id: "headline-s-growth",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "S", marketTone: "growth" },
    variantIndex: null,
    title: "市場が強く織り込む、ストップ高水準です。",
    body: "現在の数字だけでなく、これからのキャリア曲線まで査定に反映されています。このモデルでは、人的資本の伸びが主役です。",
  },
  {
    id: "headline-s-structure",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "S", marketTone: "structure" },
    variantIndex: null,
    title: "複数の収益エンジンが効く、超優良な構造です。",
    body: "給与、資産、初期ストックのうち一つだけに依存しない査定です。単発の上振れより、積み上がった構造が強みになっています。",
  },
  {
    id: "headline-a-growth",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "A", marketTone: "growth" },
    variantIndex: null,
    title: "成長の傾きまで評価された、優良銘柄です。",
    body: "現在の収入に加えて、残りのキャリアで生まれるキャッシュフローが時価総額を押し上げています。伸びの余白を持つタイプです。",
  },
  {
    id: "headline-a-structure",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "A", marketTone: "structure" },
    variantIndex: null,
    title: "安定性と資本の土台が強い、優良銘柄です。",
    body: "派手な一点突破ではなく、継続性と資本の蓄積が査定を支えています。市場環境が変わっても、軸がぶれにくい構造です。",
  },
  {
    id: "headline-b-growth",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "B", marketTone: "growth" },
    variantIndex: null,
    title: "平均を狙える成長曲線に乗っています。",
    body: "今回の査定は、現在値よりも今後の曲線に見どころがあります。小さな条件差が、残余年数の中で広がる局面です。",
  },
  {
    id: "headline-b-structure",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "B", marketTone: "structure" },
    variantIndex: null,
    title: "派手さより再現性で積み上げる、安定株です。",
    body: "一発の上振れより、継続して稼ぐ力と守る力が査定の中心です。長期で見るほど、土台の強さが効きます。",
  },
  {
    id: "headline-c-growth",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "C", marketTone: "growth" },
    variantIndex: null,
    title: "現在値より、伸ばせるレバーが見えやすい局面です。",
    body: "査定はまだ発展途上ですが、キャリア曲線や時間軸に改善余地が残っています。結果は現在の固定評価ではなく、入力条件上の現在地です。",
  },
  {
    id: "headline-c-structure",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "C", marketTone: "structure" },
    variantIndex: null,
    title: "査定は控えめでも、土台を整える余地があります。",
    body: "数字の大きさより、どの項目が査定を支え切れていないかを読み解く結果です。構造が見えれば、再計算の比較も意味を持ちます。",
  },
  {
    id: "headline-d-growth",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "D", marketTone: "growth" },
    variantIndex: null,
    title: "再建プランを読み解く、改善余地の大きい局面です。",
    body: "このモデルでは、現在の収入・資産・時間軸のいずれかがまだ査定へ十分に乗っていません。将来を断定する結果ではなく、条件を見直すための起点です。",
  },
  {
    id: "headline-d-structure",
    slot: "headline",
    category: "市場見出し",
    match: { tier: "D", marketTone: "structure" },
    variantIndex: null,
    title: "まずは現在の構造を把握するところから始まります。",
    body: "査定額そのものより、給与・資産・残余年数のどこが小さいかを確認する結果です。人間の価値ではなく、この簡易モデル上の評価です。",
  },
  {
    id: "career-runway-01",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "runway" },
    variantIndex: 0,
    title: "まだ助走。現在額より、これからの傾きが重要です。",
    body: "職業ピークまで時間があり、キャリア曲線の上昇分が査定に効く位置です。今の年収だけでは、モデル上の伸びを読み切れません。",
  },
  {
    id: "career-runway-02",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "runway" },
    variantIndex: 1,
    title: "時間を味方にできる、長い滑走路があります。",
    body: "残余就労年数が長いため、毎年のわずかな差が累計では大きくなります。今回の時価総額は、時間そのものも資産として扱っています。",
  },
  {
    id: "career-runway-03",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "runway" },
    variantIndex: 2,
    title: "将来の選択肢が、現在の査定を支えています。",
    body: "収入の水準だけでなく、職業カーブがこれからどこまで伸びる設定かが重要です。短期の比較より、生涯曲線を見るタイプです。",
  },
  {
    id: "career-growth-01",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "growth" },
    variantIndex: 0,
    title: "収入曲線が、いま査定を押し上げる時期です。",
    body: "職業ピークに近づく途中にあり、給与所得の伸びが最も価値を持ちやすい局面です。現在の積み上げが、後半の選択肢を広げます。",
  },
  {
    id: "career-growth-02",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "growth" },
    variantIndex: 1,
    title: "人的資本の伸びが見えやすい成長局面です。",
    body: "現在の収入はスタート地点であり、モデルではその先のカーブも評価しています。年齢ではなく、職業上の成長局面にいることがポイントです。",
  },
  {
    id: "career-growth-03",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "growth" },
    variantIndex: 2,
    title: "今は、稼ぐ力を曲線に変えるフェーズです。",
    body: "残りのキャリアに上昇余地があり、所得の累積が査定を支えます。資産の話だけでなく、専門性の更新が効く時間帯です。",
  },
  {
    id: "career-peak-01",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "peak" },
    variantIndex: 0,
    title: "今の稼ぐ力を、次の資本へ変える局面です。",
    body: "職業上の収入曲線が高い位置にあり、給与所得の存在感が大きくなります。今回の見どころは、ピークの年収水準そのものです。",
  },
  {
    id: "career-peak-02",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "peak" },
    variantIndex: 1,
    title: "キャリアの値札が、もっとも厚くなりやすい時期です。",
    body: "現在の年収と職業特性が、時価総額へ強く反映されています。モデル上は、時間の長さよりも今のキャッシュフローの厚みが主役です。",
  },
  {
    id: "career-peak-03",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "peak" },
    variantIndex: 2,
    title: "山の高さを、どう使うかを見るフェーズです。",
    body: "収入曲線の上昇より、現在の水準をどのような構造に変えていくかが見どころです。資産推移とあわせて読むと、査定の性格が分かります。",
  },
  {
    id: "career-late-01",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "late" },
    variantIndex: 0,
    title: "後半戦は、継続性と資本の防御力が主役です。",
    body: "残余就労年数が限られるため、このモデルでは給与の成長率より既存ストックの寄与が相対的に大きくなります。",
  },
  {
    id: "career-late-02",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "late" },
    variantIndex: 1,
    title: "時間より、現在の土台が査定を支える局面です。",
    body: "これからの年数が短いほど、初期資産や安定したキャッシュフローの意味が増します。収入曲線の派手さだけでは測れない段階です。",
  },
  {
    id: "career-late-03",
    slot: "career",
    category: "キャリアの時間軸",
    match: { timePhase: "late" },
    variantIndex: 2,
    title: "キャリアの終盤は、守備力も価値になります。",
    body: "就労期間の残りを前提に、査定の重心が将来の上昇から現在の構造へ移っています。資産と継続性を一緒に見る結果です。",
  },
  {
    id: "risk-stable-01",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "stable" },
    variantIndex: 0,
    title: "長い給与キャッシュフローが、査定の下支えです。",
    body: "職業上の継続性が高く、モデルでは大きな断絶を見込みにくい設定です。派手な上振れより、時間をかけた安定感が強みです。",
  },
  {
    id: "risk-stable-02",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "stable" },
    variantIndex: 1,
    title: "下振れの小ささが、静かに効くタイプです。",
    body: "将来の所得が連続しやすい前提のため、残余年数がそのまま価値になりやすい構造です。再現性を重視する査定になっています。",
  },
  {
    id: "risk-resilient-01",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "resilient" },
    variantIndex: 0,
    title: "継続性を土台に、専門性の更新が効く構造です。",
    body: "安定したキャリア特性を持ちながらも、評価を保つには職業上の能力更新が重要になります。守りと成長の中間にいるタイプです。",
  },
  {
    id: "risk-resilient-02",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "resilient" },
    variantIndex: 1,
    title: "安定の中に、伸びしろを残すキャリアです。",
    body: "急激な変動は想定されにくい一方、完全に固定された曲線でもありません。長期の継続性が査定のベースです。",
  },
  {
    id: "risk-balanced-01",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "balanced" },
    variantIndex: 0,
    title: "成長余地と変動を、同時に持つ銘柄性です。",
    body: "伸びる可能性はありますが、毎年同じ曲線を前提にはできません。今回の査定は、上昇と変動の両方を含んだ期待値です。",
  },
  {
    id: "risk-balanced-02",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "balanced" },
    variantIndex: 1,
    title: "期待値は中立。差が出るのは継続の質です。",
    body: "現在の収入だけでなく、キャリアがどれだけ連続するかが査定を動かします。専門性の更新が曲線を支える前提です。",
  },
  {
    id: "risk-volatile-01",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "volatile" },
    variantIndex: 0,
    title: "伸びしろは大きい一方、曲線の再現性も要チェックです。",
    body: "高い査定は上振れの可能性を含んでいますが、安定して同じ水準が続くことを意味しません。リスクも含めた期待値です。",
  },
  {
    id: "risk-volatile-02",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "volatile" },
    variantIndex: 1,
    title: "波の大きさまで含めて、評価されるキャリアです。",
    body: "収入の上昇余地と変動はセットでモデルに入っています。時価総額は、毎年の確定額ではなく生涯の簡易シナリオです。",
  },
  {
    id: "risk-extreme-01",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "extreme" },
    variantIndex: 0,
    title: "期待値は強気。再現性は別途、検証が必要です。",
    body: "上振れの可能性が査定を押し上げる一方で、職業上の変動も大きく設定されています。スコアの高さを、安定性の保証としては読まないでください。",
  },
  {
    id: "risk-extreme-02",
    slot: "career",
    category: "キャリア変動リスク",
    match: { riskBucket: "extreme" },
    variantIndex: 1,
    title: "高ボラティリティの成長株。値動きも査定の一部です。",
    body: "この結果は、急成長の可能性と大きな変動を同時に織り込んだものです。年収推移の山と、キャリアリスクを並べて見ると構造が分かります。",
  },
  {
    id: "capital-human-01",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "human" },
    variantIndex: 0,
    title: "最大の資産は、まだ人的資本です。",
    body: "時価総額の中心は、これから働いて生み出す給与所得です。現在の専門性と残余年数が、最も大きなエンジンになっています。",
  },
  {
    id: "capital-human-02",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "human" },
    variantIndex: 1,
    title: "いちばん大きいストックは、あなたの稼ぐ力です。",
    body: "資産所得より、キャリアが生むキャッシュフローの存在感が大きい査定です。年収だけでなく、曲線の持続性が重要になります。",
  },
  {
    id: "capital-human-03",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "human" },
    variantIndex: 2,
    title: "いまの主力事業は、人的資本です。",
    body: "このモデルでは、現在から就労終了までの給与所得が時価総額を主に支えています。職業カーブと時間軸を読む結果です。",
  },
  {
    id: "capital-compound-01",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "compound" },
    variantIndex: 0,
    title: "複利は、まだ助走中です。",
    body: "現時点では給与所得が主役でも、長い時間軸と再投資が後半の資産曲線を押し上げる構造です。時間が働くタイプです。",
  },
  {
    id: "capital-compound-02",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "compound" },
    variantIndex: 1,
    title: "小さな積み上げが、後半で存在感を増します。",
    body: "資産所得の金額だけではなく、残余年数と再投資率の組み合わせに価値があります。このモデルでは、継続の差が複利の差になります。",
  },
  {
    id: "capital-compound-03",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "compound" },
    variantIndex: 2,
    title: "収入の一部が、次の収入をつくる段階です。",
    body: "再投資が資産残高へ入り、その運用益がさらに累積する設定です。現在の査定より、資産推移の後半に特徴が出ます。",
  },
  {
    id: "capital-capital-01",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "capital" },
    variantIndex: 0,
    title: "すでに資本を持つ人の査定です。",
    body: "初期資産が時価総額の大きな土台になっています。給与の変動だけでなく、既存ストックがどのように寄与するかが見どころです。",
  },
  {
    id: "capital-capital-02",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "capital" },
    variantIndex: 1,
    title: "給与より先に、元本が働いています。",
    body: "このモデルでは、開始時点の資産も時価総額へ別枠で加算されます。稼ぐ力と同時に、保有するストックが評価の中心です。",
  },
  {
    id: "capital-capital-03",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "capital" },
    variantIndex: 2,
    title: "資本ストックが、査定の耐久力をつくっています。",
    body: "初期資産の寄与が大きいため、年収の短期的な変化だけでは結果が決まりません。内訳を読むほど、構造の強さが分かります。",
  },
  {
    id: "capital-dual-01",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "dual" },
    variantIndex: 0,
    title: "稼ぐ力と回るお金が、同時に働いています。",
    body: "給与所得と資産由来の寄与が両方とも査定を支える構造です。一つの収益源へ依存しないことが、数字の厚みになっています。",
  },
  {
    id: "capital-dual-02",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "dual" },
    variantIndex: 1,
    title: "人的資本と金融資本の、二つのエンジンです。",
    body: "キャリアのキャッシュフローと資産の積み上がりが並走しています。時価総額の内訳に、二刀流の特徴が表れます。",
  },
  {
    id: "capital-dual-03",
    slot: "capital",
    category: "時価総額の源泉",
    match: { capitalStyle: "dual" },
    variantIndex: 2,
    title: "収入とストックが、互いを補う査定です。",
    body: "現在の給与だけでも、初期資産だけでも説明しきれない結果です。複数の要因が効いていることが、このタイプの強みです。",
  },
  {
    id: "quiz-master-01",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "master" },
    variantIndex: 0,
    title: "判断のOSが強い。",
    body: "今回の5問では、複利・リスク・一貫性に関する原則を安定して捉えられています。このモデルでは、その理解が実効利回りの補正に反映されます。",
  },
  {
    id: "quiz-master-02",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "master" },
    variantIndex: 1,
    title: "数字と感情を、切り分けて考えられるタイプです。",
    body: "すべての出題セットで正答しました。知識量だけでなく、条件が変わっても判断を一貫させる力が結果に表れています。",
  },
  {
    id: "quiz-master-03",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "master" },
    variantIndex: 2,
    title: "利回りの前に、判断の土台が整っています。",
    body: "5点満点は、このランダム出題に対する結果です。将来を保証するものではありませんが、今回のテーマでは強い再現性が見えました。",
  },
  {
    id: "quiz-steady-01",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "steady" },
    variantIndex: 0,
    title: "金融判断は堅実。細部の復習でさらに磨けます。",
    body: "多くの原則は捉えられています。今回の誤答は、数字の計算か、状況に応じた判断の一貫性に関する可能性があります。",
  },
  {
    id: "quiz-steady-02",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "steady" },
    variantIndex: 1,
    title: "基礎体力は十分。残る差は判断の細部です。",
    body: "3〜4点は、重要な考え方を概ね押さえている状態です。結果画面の解説を見ると、どの条件で判断が変わったかを確認できます。",
  },
  {
    id: "quiz-steady-03",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "steady" },
    variantIndex: 2,
    title: "大きく外さない、実務的な金融感覚です。",
    body: "すべてを正解するより、判断の軸を持つことが重要です。今回の結果には、その軸がすでに見えています。",
  },
  {
    id: "quiz-developing-01",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "developing" },
    variantIndex: 0,
    title: "伸びしろは、知識より判断の順番にあります。",
    body: "2点という結果は、今回出題されたテーマで見直せる箇所があるというサインです。正解と解説を並べると、思考の分岐点が分かります。",
  },
  {
    id: "quiz-developing-02",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "developing" },
    variantIndex: 1,
    title: "いまは、原則を自分の言葉にする途中です。",
    body: "複利やリスクの知識は、条件が変わると判断が揺れやすいテーマです。今回の復習は、次の意思決定を断定するものではなく、考え方を整える材料です。",
  },
  {
    id: "quiz-developing-03",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "developing" },
    variantIndex: 2,
    title: "点数より、どこで迷ったかに価値があります。",
    body: "2点は中間の結果です。間違えたテーマを一つずつ見ることで、知識の穴ではなく判断のクセを確認できます。",
  },
  {
    id: "quiz-review-01",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "review" },
    variantIndex: 0,
    title: "今回のテーマでは、復習が時価総額の隠れたレバーです。",
    body: "0〜1点は、出題された判断原則と現在の感覚に差があった結果です。人格評価ではなく、解説を読むための入口として扱ってください。",
  },
  {
    id: "quiz-review-02",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "review" },
    variantIndex: 1,
    title: "数字の前に、判断の型を整える余地があります。",
    body: "今回のクイズは、計算力だけでなく、損失や時間への感じ方も扱っています。正答数だけで結論を出さず、各セットの解説を確認してみてください。",
  },
  {
    id: "quiz-review-03",
    slot: "insight",
    category: "クイズ総合評価",
    match: { quizBand: "review" },
    variantIndex: 2,
    title: "苦手の発見は、モデル上の改善余地です。",
    body: "出題はランダムな5セットであり、0〜1点が人としての能力を表すわけではありません。今回のテーマにおける判断の傾向として読む結果です。",
  },
  {
    id: "theme-math-01",
    slot: "insight",
    category: "クイズテーマ別",
    match: { quizTheme: "math" },
    variantIndex: 0,
    title: "額面より、実質と掛け算を確認したい局面です。",
    body: "金利、複利、インフレ、手数料は、見た目の数字と実際の影響がずれやすいテーマです。今回の解説で、率と時間の関係を確認できます。",
  },
  {
    id: "theme-math-02",
    slot: "insight",
    category: "クイズテーマ別",
    match: { quizTheme: "math" },
    variantIndex: 1,
    title: "数字の直感を、もう一段だけ精密に。",
    body: "足し算の感覚では捉えにくい複利や変動率が、今回のつまずきになった可能性があります。正解は暗記ではなく、計算の仕組みとして読むのが向いています。",
  },
  {
    id: "theme-risk-01",
    slot: "insight",
    category: "クイズテーマ別",
    match: { quizTheme: "risk" },
    variantIndex: 0,
    title: "期待値だけでなく、退場しない設計も論点です。",
    body: "保険、集中投資、賭け金の問題では、利益の大きさと損失への耐久力を分けて考える必要があります。今回の解説は、その境界を扱っています。",
  },
  {
    id: "theme-risk-02",
    slot: "insight",
    category: "クイズテーマ別",
    match: { quizTheme: "risk" },
    variantIndex: 1,
    title: "リターンを見る目に、守備力を加える余地があります。",
    body: "同じ期待値でも、一度の損失で続けられなくなるなら意味が変わります。出題された条件の違いを、リスクの大きさとして読み直してみてください。",
  },
  {
    id: "theme-bias-01",
    slot: "insight",
    category: "クイズテーマ別",
    match: { quizTheme: "bias" },
    variantIndex: 0,
    title: "数字の問題ではなく、物語に引っ張られやすい局面です。",
    body: "サンクコスト、保有効果、損失回避は、人に自然に起きる判断のクセです。知識不足ではなく、条件を見直す余白を持てるかがポイントです。",
  },
  {
    id: "theme-bias-02",
    slot: "insight",
    category: "クイズテーマ別",
    match: { quizTheme: "bias" },
    variantIndex: 1,
    title: "過去の自分より、いまの選択肢を見たいテーマです。",
    body: "すでに払ったお金、手に入れたもの、直前の利益は判断を偏らせやすくなります。今回の解説は、現在の価値だけで考える練習になります。",
  },
  {
    id: "theme-consistency-01",
    slot: "insight",
    category: "クイズテーマ別",
    match: { quizTheme: "consistency" },
    variantIndex: 0,
    title: "条件が変わっても、判断の軸を保てるかがテーマです。",
    body: "時間や価格の見え方が変わると、同じ取引でも答えが揺れやすくなります。今回の出題は、その一貫性を確かめる内容です。",
  },
  {
    id: "theme-consistency-02",
    slot: "insight",
    category: "クイズテーマ別",
    match: { quizTheme: "consistency" },
    variantIndex: 1,
    title: "目先と長期で、同じ基準を使えるかを確認したい結果です。",
    body: "1週間の価値や同額の割引は、状況の見せ方で感覚が変わるテーマです。正解パターンを通じて、自分の判断ルールを言葉にできます。",
  },
  {
    id: "position-top10-01",
    slot: "position",
    category: "市場ポジション",
    match: { positionBand: "top10" },
    variantIndex: 0,
    title: "市場の上位10%。注目銘柄の位置です。",
    body: "この順位は、保存されている査定履歴との比較です。入力条件が異なる利用者を含むため、人間としての優劣ではなく、モデル上の相対位置を表します。",
  },
  {
    id: "position-top10-02",
    slot: "position",
    category: "市場ポジション",
    match: { positionBand: "top10" },
    variantIndex: 1,
    title: "分布の上側に、明確に位置しています。",
    body: "時価総額の大きさだけでなく、現在の比較対象の中で上位にいる結果です。共有するなら、内訳も一緒に見ると特徴が伝わります。",
  },
  {
    id: "position-top30-01",
    slot: "position",
    category: "市場ポジション",
    match: { positionBand: "top30" },
    variantIndex: 0,
    title: "市場平均をアウトパフォームする位置です。",
    body: "上位30%以内は、今回のランキング分布で平均より上側にいる状態です。順位は変動するため、内訳と合わせて読むのが向いています。",
  },
  {
    id: "position-top30-02",
    slot: "position",
    category: "市場ポジション",
    match: { positionBand: "top30" },
    variantIndex: 1,
    title: "上位グループに入り、次の差が見え始めています。",
    body: "ここからの違いは、時価総額の大きさだけでなく、給与・資産・時間軸のどれが主力かに表れます。",
  },
  {
    id: "position-above-01",
    slot: "position",
    category: "市場ポジション",
    match: { positionBand: "aboveMarket" },
    variantIndex: 0,
    title: "市場の中央より、一歩前に出ています。",
    body: "偏差値と上位率の比較では、平均より上側に位置する結果です。派手な順位より、何が査定を支えるかに注目してください。",
  },
  {
    id: "position-above-02",
    slot: "position",
    category: "市場ポジション",
    match: { positionBand: "aboveMarket" },
    variantIndex: 1,
    title: "市場平均を、構造で上回る位置です。",
    body: "結果はランキング上の一地点ですが、時価総額の源泉は人によって異なります。今回の強みが給与か資本かを読むと、比較が立体的になります。",
  },
  {
    id: "position-rebuild-01",
    slot: "position",
    category: "市場ポジション",
    match: { positionBand: "rebuild" },
    variantIndex: 0,
    title: "市場比較では、伸びしろが見えやすい現在地です。",
    body: "ランキングは査定履歴に基づく相対比較です。低い順位を人の価値に置き換えず、モデル上のレバーを見つけるために使ってください。",
  },
  {
    id: "position-rebuild-02",
    slot: "position",
    category: "市場ポジション",
    match: { positionBand: "rebuild" },
    variantIndex: 1,
    title: "分布の中では、これから条件差を作れる位置です。",
    body: "時価総額は入力条件に強く依存します。順位そのものより、給与・資産・再投資・クイズのどれが差になったかを見る結果です。",
  },
  {
    id: "delta-up",
    slot: "insight",
    category: "前回比",
    match: { deltaBand: "up" },
    variantIndex: null,
    title: "前回比・急騰。",
    body: "今回の差分は {{delta}} です。変更した入力条件を一つだけ確認すると、このモデルで最も査定を動かすレバーが見つかります。",
  },
  {
    id: "delta-flat",
    slot: "insight",
    category: "前回比",
    match: { deltaBand: "flat" },
    variantIndex: null,
    title: "前回比・小動き。",
    body: "今回の差分は {{delta}} です。条件を変えても大きく動かなかったなら、時価総額を支える土台が比較的安定している可能性があります。",
  },
  {
    id: "delta-down",
    slot: "insight",
    category: "前回比",
    match: { deltaBand: "down" },
    variantIndex: null,
    title: "前回比・調整局面。",
    body: "今回の差分は {{delta}} です。これは前回より人としての価値が下がったという意味ではなく、変更後の入力条件に対するモデル上の差です。",
  },
  {
    id: "title-gekokujo",
    slot: "special",
    category: "隠し称号",
    match: { titleKey: "gekokujo" },
    variantIndex: null,
    title: "隠し称号：下剋上",
    body: "この称号は、学歴入力と職業選択の意外な組み合わせで発火します。モデル内のキャリア補正より、現在の職業設定が強く物語をつくる結果です。",
  },
  {
    id: "title-high-education-working-poor",
    slot: "special",
    category: "隠し称号",
    match: { titleKey: "high-education-working-poor" },
    variantIndex: null,
    title: "隠し称号：高学歴ワーキングプア",
    body: "この称号は、キャリア乗数と現在の雇用条件にギャップがある組み合わせです。称号は演出であり、人生や能力を決めつけるものではありません。",
  },
  {
    id: "title-treasure-wasted",
    slot: "special",
    category: "隠し称号",
    match: { titleKey: "treasure-wasted" },
    variantIndex: null,
    title: "隠し称号：宝の持ち腐れ",
    body: "自己評価に基づく外見補正と、極変動の職業設定がぶつかることで発火します。査定では、上振れと変動の両方が強く表れる組み合わせです。",
  },
  {
    id: "title-unemployed-capitalist",
    slot: "special",
    category: "隠し称号",
    match: { titleKey: "unemployed-capitalist" },
    variantIndex: null,
    title: "隠し称号：無職という名の資本家",
    body: "このモデルでは、収入がなくても初期資産と資産運用の寄与を評価します。働き方と資本ストックを切り離して読む、象徴的な称号です。",
  },
  {
    id: "title-ai-top-pick",
    slot: "special",
    category: "隠し称号",
    match: { titleKey: "ai-top-pick" },
    variantIndex: null,
    title: "隠し称号：2026最有力銘柄候補",
    body: "若い年齢、AIエンジニア設定、S Tierの三条件がそろうと発火します。期間限定の成長仮定を含む、モデル固有の強気シナリオです。",
  },
  {
    id: "title-ev-millionaire",
    slot: "special",
    category: "隠し称号",
    match: { titleKey: "ev-millionaire" },
    variantIndex: null,
    title: "隠し称号：EVだけは億万長者",
    body: "金融判断の満点と少額の金融資産、ポーカー職を組み合わせた演出です。期待値の理解と実際の資本量は別、というギャップを楽しむ称号です。",
  },
  {
    id: "title-quiet-capitalist",
    slot: "special",
    category: "隠し称号",
    match: { titleKey: "quiet-capitalist" },
    variantIndex: null,
    title: "隠し称号：静かなる資本家",
    body: "安定職、高い資産、継続的な再投資の組み合わせで発火します。派手な上振れより、積み上げの一貫性を称える演出です。",
  },
  {
    id: "title-perfect-average",
    slot: "special",
    category: "隠し称号",
    match: { titleKey: "perfect-average" },
    variantIndex: null,
    title: "隠し称号：完全なる市場平均",
    body: "偏差値がちょうど50.0になったときだけ発火します。上でも下でもない一点を、モデルの市場平均として遊ぶ称号です。",
  },
  {
    id: "fallback-standard",
    slot: "fallback",
    category: "フォールバック",
    match: { fallbackKind: "standard" },
    variantIndex: null,
    title: "今回の査定は、複数の条件が重なってできています。",
    body: "数字の大小だけでなく、給与・資産・時間軸の内訳を見ると、このモデルが何を評価したかを確認できます。",
  },
  {
    id: "fallback-ranking-wait",
    slot: "fallback",
    category: "フォールバック",
    match: { fallbackKind: "ranking-wait" },
    variantIndex: null,
    title: "市場ポジションを照合中です。",
    body: "時価総額は先に算出できています。ランキングが取得でき次第、査定履歴の中での相対位置も確認できます。",
  },
  {
    id: "fallback-boundary",
    slot: "fallback",
    category: "フォールバック",
    match: { fallbackKind: "boundary" },
    variantIndex: null,
    title: "境界線上にいる、複合型の結果です。",
    body: "一つのラベルだけでは説明しにくい査定です。給与・資産・職業カーブのうち、もっとも大きい寄与を主軸として読み解いてください。",
  },
];

export function assertCatalogIntegrity(): void {
  if (COMMENT_CATALOG.length !== 86) {
    throw new Error(`COMMENT_CATALOG length must be 86, got ${COMMENT_CATALOG.length}`);
  }
  const ids = new Set(COMMENT_CATALOG.map((e) => e.id));
  if (ids.size !== 86) {
    throw new Error(`COMMENT_CATALOG ids must be unique, got ${ids.size}`);
  }
}

